### ISSUE TITLE
backface-visibility issue on Mozilla

### ISSUE THREAD

**Issue by mburakerman** [mburakerman/memorizr#1]
If you check Memorizr on Mozilla, you can see that images are seen because of Mozilla's `backface-visibility` [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1201471) .

I have tried some solutions i find on stackoverflow like [this](https://stackoverflow.com/a/24517380/4991434) and [this](https://stackoverflow.com/a/32421734/4991434) but still have that issue. 

So, i need your help. Thanks in advance!

**Comment by TenjiTenno** [comment]
I use only your bg on http://добрыевещи.копьёв.рф / 

about opacity of containers of your game can say only one.. you can use full color as
background: #FFFFFF;
so they will not be visible through

**Comment by mburakerman** [comment]
A yes. 
You have gave me an idea. I can play with opacity of images so there won't be issue i think.
I always tried to solve this issue with `transform ` or `backface-visibiliy` but never tried `opacity`.
Will try now!

**Comment by mburakerman** [comment]
Fixed the issue playing with images opacity. Thanks to @TenjiTenno !
